// Builds the website into the top of this folder (index.html, 404.html, app.*.js/css,
// assets/, fonts/, vendor/) and the single-file live preview into build/preview.html.
//   npm run build            (optional: PUBLIC_URL=https://... bakes the share image address)
import { build, transform } from 'esbuild';
import { readFileSync, writeFileSync, mkdirSync, readdirSync, rmSync, copyFileSync, existsSync } from 'node:fs';
import { join, dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { createHash } from 'node:crypto';
import { DEFAULTS } from '../shared/catalog.js';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const P = (...a) => join(ROOT, ...a);
const SRC_ASSETS = P('assets-src');
const hash = (s) => createHash('sha256').update(s).digest('hex').slice(0, 8);
const PUBLIC_URL = (process.env.PUBLIC_URL || '').replace(/\/+$/, '');

if (existsSync(P('public'))) rmSync(P('public'), { recursive: true, force: true }); // old layout
mkdirSync(P('assets', 'parts'), { recursive: true });
mkdirSync(P('vendor'), { recursive: true });
mkdirSync(P('fonts'), { recursive: true });
mkdirSync(P('build'), { recursive: true });

// ---------------------------------------------------------------- logo assets
const meta = JSON.parse(readFileSync(join(SRC_ASSETS, 'parts.json'), 'utf8')).parts.filter((p) => p.id !== 'dust');
const files = ['logo-1200.png', 'logo-520.png', 'favicon-32.png', 'icon-192.png', 'icon-512.png', 'apple-touch-icon.png', 'social-spot-mark.svg', 'social-spot-16.png', 'social-spot-32.png', 'social-spot-48.png', 'social-spot-96.png', 'social-spot-192.png', 'social-spot-512.png', 'social-spot-touch.png', 'social-spot-maskable.png', 'og.png', 'og.jpg'];
for (const f of files) copyFileSync(join(SRC_ASSETS, f), P('assets', f));
copyFileSync(join(SRC_ASSETS, 'favicon.ico'), P('favicon.ico'));
for (const p of meta) copyFileSync(join(SRC_ASSETS, 'parts', `${p.id}.png`), P('assets', 'parts', `${p.id}.png`));
copyFileSync(join(SRC_ASSETS, 'social-spot-logo-original.png'), P('assets', 'social-spot-logo.png'));

// ---------------------------------------------------------------- venue photos
// scripts/prepare_photos.py writes the images to assets/photos/ and lists them here
const photoGen = join(SRC_ASSETS, 'photos', 'photos.gen.json');
const photos = existsSync(photoGen) ? JSON.parse(readFileSync(photoGen, 'utf8')).photos : {};

const QR_VER = '1.4.4';
const JSQR_VER = '1.4.0';
const nm = (...a) => P('node_modules', ...a);
if (existsSync(nm('qrcode-generator', 'qrcode.js'))) {
  copyFileSync(nm('qrcode-generator', 'qrcode.js'), P('vendor', 'qrcode.js'));
  copyFileSync(nm('jsqr', 'dist', 'jsQR.js'), P('vendor', 'jsQR.js'));
}

// paths are relative: they resolve against the page's <base>, so the site works at
// https://domain/ and at https://user.github.io/repo/ alike
const serverAssets = {
  logo: 'assets/logo-1200.png',
  logoSmall: 'assets/logo-520.png',
  parts: Object.fromEntries(meta.map((p) => [p.id, `assets/parts/${p.id}.png`])),
  partsMeta: meta,
  photos,
  qrLib: 'vendor/qrcode.js',
  jsqrLib: 'vendor/jsQR.js',
};
const dataUri = (file) => `data:image/png;base64,${readFileSync(file).toString('base64')}`;
const previewAssets = {
  logo: dataUri(join(SRC_ASSETS, 'logo-1200.png')),
  logoSmall: dataUri(join(SRC_ASSETS, 'logo-520.png')),
  parts: Object.fromEntries(meta.map((p) => [p.id, dataUri(join(SRC_ASSETS, 'parts', `${p.id}.png`))])),
  partsMeta: meta,
  photos: {}, // the single-file preview leaves the photos out to stay small
  qrLib: `https://cdn.jsdelivr.net/npm/qrcode-generator@${QR_VER}/qrcode.js`,
  jsqrLib: `https://cdn.jsdelivr.net/npm/jsqr@${JSQR_VER}/dist/jsQR.js`,
};
writeFileSync(P('src', 'assets-server.gen.js'), `// generated by scripts/build.js\nexport const ASSETS = ${JSON.stringify(serverAssets, null, 1)};\n`);
writeFileSync(P('src', 'assets-preview.gen.js'), `// generated by scripts/build.js\nexport const ASSETS = ${JSON.stringify(previewAssets)};\n`);

// ---------------------------------------------------------------- fonts (self-hosted)
const FONTS = [
  ['DM Sans', 'dm-sans', [400, 500, 600, 700, 800]],
  ['Barlow Condensed', 'barlow-condensed', [600, 700]],
  ['Manrope', 'manrope', [400, 500, 600, 700, 800]],
  ['IBM Plex Mono', 'ibm-plex-mono', [400, 500, 600]],
];
let fontCss = '';
for (const [family, pkg, weights] of FONTS) {
  const license = nm('@fontsource', pkg, 'LICENSE');
  if (existsSync(license)) copyFileSync(license, P('fonts', `${pkg}-LICENSE.txt`));
  for (const w of weights) {
    const file = `${pkg}-latin-${w}-normal.woff2`;
    const src = nm('@fontsource', pkg, 'files', file);
    if (existsSync(src)) copyFileSync(src, P('fonts', file));
    fontCss += `@font-face{font-family:'${family}';font-style:normal;font-weight:${w};font-display:swap;src:url(fonts/${file}) format('woff2');unicode-range:U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD}\n`;
  }
}

// ---------------------------------------------------------------- CSS + JS
const styles = ['styles.css', 'experience.css'].map((file) => readFileSync(P('src', file), 'utf8')).join('\n');
const cssMin = (await transform(styles, { loader: 'css', minify: true, target: ['chrome80', 'safari13', 'firefox78'] })).code;
const siteCss = fontCss + cssMin;
const common = { bundle: true, minify: true, format: 'iife', target: ['es2019'], legalComments: 'none', logLevel: 'warning' };
const siteJs = (await build({ ...common, entryPoints: [P('src', 'main-server.js')], write: false })).outputFiles[0].text;
const previewJs = (await build({ ...common, entryPoints: [P('src', 'main-preview.js')], write: false })).outputFiles[0].text;

for (const f of readdirSync(ROOT)) if (/^app\.[0-9a-f]{8}\.(js|css)$/.test(f)) rmSync(P(f));
const jsName = `app.${hash(siteJs)}.js`;
const cssName = `app.${hash(siteCss)}.css`;
writeFileSync(P(jsName), siteJs);
writeFileSync(P(cssName), siteCss);

// ---------------------------------------------------------------- index.html + 404.html
// This small inline script sets the base before static icon tags are parsed, and
// works out where the site lives, so every file loads from the right folder:
//  - served by the Social Spot server: the server fills in ss-base="/"
//  - index.html on a static host: the folder index.html was loaded from
//  - 404.html on GitHub Pages (deep links like /repo/t/abc): the /repo/ folder,
//    or '/' when the site has its own domain
// first path segments the app itself uses; on GitHub Pages anything else is the repo folder
const ROUTE_ROOTS = 'replay|book|quiz|tickets|t|p|b|admin|404';
const BASE_SCRIPT = `(function(){var d=document,m=d.querySelector('meta[name="ss-base"]'),b=m&&m.getAttribute('content'),p=location.pathname;if(!b){if(d.documentElement.hasAttribute('data-404')){var s=p.split('/').filter(Boolean),h=location.hostname;b=(/\\.github\\.io$/i.test(h)||h==='localhost'||h==='127.0.0.1')&&s.length&&!/^(${ROUTE_ROOTS})$/.test(s[0])?'/'+s[0]+'/':'/';}else{b=p.slice(0,p.lastIndexOf('/')+1)||'/';}}window.SS_BASE=b;var h=d.head;function add(t,a){var e=d.createElement(t);for(var k in a)e.setAttribute(k,a[k]);h.appendChild(e);return e;}add('base',{href:b});['barlow-condensed-latin-700-normal.woff2','dm-sans-latin-400-normal.woff2'].forEach(function(f){add('link',{rel:'preload',as:'font',type:'font/woff2',crossorigin:'anonymous',href:b+'fonts/'+f});});add('link',{rel:'stylesheet',href:b+'${cssName}'});['config.js','${jsName}'].forEach(function(f){var e=d.createElement('script');e.src=b+f;e.async=false;h.appendChild(e);});})();`;
// structured data so search engines can show the venue and The Replay as an event
const V = DEFAULTS.venue, E = DEFAULTS.event;
const abs = (path) => (PUBLIC_URL ? `${PUBLIC_URL}/${path}` : path);
const venueLd = { '@type': 'SportsActivityLocation', name: V.name, description: 'Football turf, gym, steam and sauna, penthouse stays and Quiz Night every Saturday.', telephone: V.phone, image: abs('assets/og.jpg'), address: { '@type': 'PostalAddress', streetAddress: V.landmark, addressLocality: V.area, addressCountry: 'UG' }, ...(PUBLIC_URL ? { url: PUBLIC_URL } : {}) };
const jsonLd = JSON.stringify({ '@context': 'https://schema.org', '@graph': [venueLd, {
  '@type': 'Event', name: `${E.name}: ${E.edition}`, description: E.pitch, startDate: `${E.date}T${E.gatesOpen}:00+03:00`, eventStatus: 'https://schema.org/EventScheduled', eventAttendanceMode: 'https://schema.org/OfflineEventAttendanceMode', image: abs('assets/og.jpg'),
  location: { '@type': 'Place', name: V.name, address: venueLd.address }, organizer: { '@type': 'Organization', name: V.name, telephone: V.phone },
  ...(PUBLIC_URL ? { url: `${PUBLIC_URL}/replay`, offers: { '@type': 'AggregateOffer', priceCurrency: 'UGX', lowPrice: Math.min(...E.releases.map((r) => r.price)), highPrice: Math.max(...E.releases.map((r) => r.price)), url: `${PUBLIC_URL}/replay` } } : {}),
}] }).replace(/</g, '\\u003c');
const description = 'Social Spot, Akright City, Bwebajja: football turf, gym, steam and sauna, penthouse stays and Quiz Night every Saturday. Tickets for The Replay, Saturday 12 December 2026.';
const page = (is404) => `<!doctype html>
<html lang="en"${is404 ? ' data-404' : ''}>
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover">
<meta name="ss-base" content="">
<style>html,body{background:#0b0a0a;color:#f5f2ef;margin:0}</style>
<script>${BASE_SCRIPT}</script>
<link rel="icon" href="favicon.ico" sizes="16x16 32x32 48x48 64x64">
<link rel="icon" type="image/png" href="assets/social-spot-96.png" sizes="96x96">
<link rel="icon" type="image/svg+xml" href="assets/social-spot-mark.svg" sizes="any">
<link rel="apple-touch-icon" href="assets/social-spot-touch.png" sizes="180x180">
<link rel="manifest" href="manifest.webmanifest">
<title>Social Spot · Bwebajja</title>
<meta name="description" content="${description}">
<meta name="theme-color" content="#0b0a0a">
<meta property="og:type" content="website">
<meta property="og:title" content="Social Spot · Bwebajja">
<meta property="og:description" content="Everything worth leaving the house for.">
<meta property="og:image" content="${PUBLIC_URL ? PUBLIC_URL + '/' : ''}assets/og.jpg">
<meta property="og:image:width" content="1200">
<meta property="og:image:height" content="630">
<meta name="twitter:card" content="summary_large_image">
<meta name="twitter:title" content="Social Spot · Bwebajja">
<meta name="twitter:description" content="Everything worth leaving the house for.">
<meta name="apple-mobile-web-app-title" content="Social Spot">
<meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
<script type="application/ld+json">${jsonLd}</script>
</head>
<body>
<div id="app"><noscript><p style="padding:24px;font-family:system-ui">Social Spot needs JavaScript to sell tickets and take bookings. Call 0393 103 799.</p></noscript></div>
</body>
</html>
`;
writeFileSync(P('index.html'), page(false));
writeFileSync(P('404.html'), page(true));

// config.js belongs to whoever hosts the site: create it once, never overwrite it
if (!existsSync(P('config.js'))) {
  writeFileSync(P('config.js'), `/* Social Spot website settings.

   api: the address of the Social Spot server (it sells the tickets, takes the
   bookings and runs the staff area).

   - Leave it empty when this folder is served by the Social Spot server itself
     (Render, a VPS or Docker). That's the normal setup.
   - If these website files are hosted on GitHub Pages or Netlify instead, put
     the server's address here, for example:
       api: 'https://social-spot.onrender.com'
     Without a server the site still shows everything, with a "call us to book"
     notice. */
window.SOCIAL_SPOT = {
  api: '',
};
`);
}
writeFileSync(P('manifest.webmanifest'), JSON.stringify({
  name: 'Social Spot', short_name: 'Social Spot', start_url: '.', scope: '.', display: 'standalone', background_color: '#0b0a0a', theme_color: '#0b0a0a',
  id: '.', lang: 'en', description: 'Social Spot, Bwebajja: sport, music, wellness and stays.',
  icons: [
    { src: 'assets/social-spot-192.png', sizes: '192x192', type: 'image/png', purpose: 'any' },
    { src: 'assets/social-spot-512.png', sizes: '512x512', type: 'image/png', purpose: 'any' },
    { src: 'assets/social-spot-maskable.png', sizes: '512x512', type: 'image/png', purpose: 'maskable' },
  ],
}, null, 1));
writeFileSync(P('robots.txt'), 'User-agent: *\nDisallow: /admin\nDisallow: /t/\nDisallow: /p/\nDisallow: /b/\n');
writeFileSync(P('.nojekyll'), ''); // GitHub Pages: serve the files as they are

// ---------------------------------------------------------------- single-file preview (artifact)
const safeJs = previewJs.replace(/<\/script/gi, '<\\/script');
const preview = `<title>Social Spot</title>
<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Barlow+Condensed:wght@600;700&family=DM+Sans:wght@400;500;600;700;800&family=IBM+Plex+Mono:wght@400;500;600&family=Manrope:wght@400;500;600;700;800&display=swap">
<style>${cssMin}</style>
<div id="app"></div>
<script>${safeJs}</script>
`;
writeFileSync(P('build', 'preview.html'), preview);

console.log(`built index.html, 404.html, ${jsName} (${(siteJs.length / 1024).toFixed(0)} KB), ${cssName} (${(siteCss.length / 1024).toFixed(0)} KB), build/preview.html (${(preview.length / 1024).toFixed(0)} KB)`);
